services:
  - type: web
    name: coconut-gis-monorepo
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan migrate --force
      php artisan storage:link
    startCommand: |
      php artisan serve --host=0.0.0.0 --port 10000